# -*- coding: utf-8 -*-
"""GeceYagmurSimsek_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PfjK4-mjKI3BfPOGBOJqUq7ElxtWp4c4

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""



"""Describe what an algorithm is."""

An algorithm is a list of rules to follow in order to solve a problem.

"""[link text](https://)Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

The brute-force regular method is by solving a particular problem by checking all the possible cases which is slow. An algorithm is a methodical set of steps that 
can be used to make calculations, resolve problems and reach decisions. With algorithmic design when there is a given problem, we are providing a step-by-step
procedure for solving it. Algorithm is more effective and independent.

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

I believe that, using algorithm in my work practices provides an effective way to problem solving. By using paramaters of algorithm, color, texture , and
using of perspective we can create good visuals, it provides a independent work area. Also, with algorithmic design, designing gets more faster and more playable.

"""Create a python dictionary for your name surname and year of birth."""

my_dict = {'name':'Gece','surname':'Simsek','birthday':'1997'}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

name = 'Gece'
if name[0] == 'a' :
  print ("my initial is a!")
else:
  print("it doesn't")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

surname = 'Simsek'
len(surname)%3 == 0
if len(surname)%3 == 0 :
  print("it is divisible")
else:
  print("not divisible")

"""Change your year of birth to 2678."""

my_dict['birthday'] = '2678'
print(my_dict)

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""